### ISSUE TITLE
Topinambour does not launch, missing germinal.gresource.xml 

### ISSUE THREAD

**Issue by rapha8l** [cedlemo/topinambour#1]
Hello,
The software builds well, though, it seems a file is missing or misnamed :

L'ouverture du fichier « /var/lib/gems/2.3.0/gems/topinambour-1.0.0/bin/../data/germinal.gresource.xml » a échoué : Aucun fichier ou dossier de ce type
/var/lib/gems/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:114:in `invoke': L'ouverture du fichier « /var/lib/gems/2.3.0/gems/topinambour-1.0.0/bin/../data/germinal.gresource » a échoué : échec de open() : Aucun fichier ou dossier de ce type (GLib::FileError)
	from /var/lib/gems/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:114:in `block in define_singleton_method'
	from /var/lib/gems/2.3.0/gems/topinambour-1.0.0/bin/topinambour:46:in `<top (required)>'
	from /usr/local/bin/topinambour:23:in `load'
	from /usr/local/bin/topinambour:23:in `<main>'

Thanks 

Raphael

**Comment by cedlemo** [comment]
Hi Raphael,

it seems that it remained some references of the old name. I have removed all of them and pushed a new version of the gem the 1.0.1 with the modifications. The git repository is updated too.

I would like to point out the fact that topinambour has not been tested a lot and that some pbs can occurs but I am here to help you for any problems you can find.

cedlemo.

**Comment by rapha8l** [comment]
Hi,

Thanks for your quick reply. It works great now (using the repository)
Thanks also for blingbling which I use also !
Have a nice day

Raphaël

**Comment by cedlemo** [comment]
>Thanks also for blingbling which I use also

Great, I am preparing a new release with a better code, a grid layout and another stuff.

Have fun with and hacking them!
