### ISSUE TITLE
Can't get a different shell working

### ISSUE THREAD

**Issue by rapha8l** [cedlemo/topinambour#2]
Hello,

It's me again :-)
I can't launch Topinambour because of fish
I tried alternatively those things in  ~/.config/Topinambour/topinambour.css  without any success :
{
  TopinambourWindow-shell: "/usr/bin/zsh";
}

{
  -TopinambourWindow-shell: "/usr/bin/zsh";
}

TopinambourWindow-shell
{
/usr/bin/zsh;
}

Thanks

**Comment by cedlemo** [comment]
Hi rapha8l,

try this to create the directory `~/.config/topinambour/` without the uppercase. It was an error in the README that I have corrected. If everything is ok you should create a topinambour.css file with : .

```
* {
 -TopinambourWindow-shell: "/usr/bin/zsh";
}
```
Please remember to get the last gem the 1.0.3.

**Comment by rapha8l** [comment]
Thanks, it works, though it doesn't launch, I'll open a new issue :)
