### ISSUE TITLE
Ruby errors at launch

### ISSUE THREAD

**Issue by rapha8l** [cedlemo/topinambour#3]
/var/lib/gems/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
/var/lib/gems/2.3.0/gems/glib2-3.0.7/lib/glib2/deprecatable.rb:112:in `const_missing': uninitialized constant GLib::RegexCompileFlags
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:136:in `block in add_matches'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:134:in `each'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:134:in `add_matches'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:128:in `configure'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:84:in `initialize'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/window.rb:48:in `new'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/window.rb:48:in `add_terminal'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/application.rb:35:in `block in initialize'
	 from /var/lib/gems/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `invoke'
	 from /var/lib/gems/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/bin/topinambour:62:in `<top (required)>'
	 from /usr/local/bin/topinambour:23:in `load'
	 from /usr/local/bin/topinambour:23:in `<main>'

Thanks

**Comment by rapha8l** [comment]
Thanks !
I've just tried and get the same error (I repaste it as it seems it has been truncated)
/var/lib/gems/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
/var/lib/gems/2.3.0/gems/glib2-3.0.7/lib/glib2/deprecatable.rb:112:in `const_missing': uninitialized constant GLib::RegexCompileFlags
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:111:in `block in add_matches'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:109:in `each'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:109:in `add_matches'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:103:in `configure'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/terminal.rb:61:in `initialize'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/window.rb:41:in `new'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/window.rb:41:in `add_terminal'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/lib/application.rb:35:in `block in initialize'
	 from /var/lib/gems/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `invoke'
	 from /var/lib/gems/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from /var/lib/gems/2.3.0/gems/topinambour-1.0.3/bin/topinambour:62:in `<top (required)>'
	 from /usr/local/bin/topinambour:23:in `load'
	 from /usr/local/bin/topinambour:23:in `<main>'

**Comment by cedlemo** [comment]
Ok I know. It is because I use the ruby-gnome2 git versions and the GLib gem that supports Regex has not been released yet.

I have disabled the regex and updated the gem to 1.0.5.

Sorry if it looks messy but I use the last version of the ruby-gnome2 gems  because I contribute to it and I forget sometimes that it is not the versions that people use.

**Comment by rapha8l** [comment]
I'm using your github repo, and it tells me it's up to date with 1.0.3 :)

**Comment by cedlemo** [comment]
How do you install the gem, please use : 

    gem install topinambour

**Comment by rapha8l** [comment]
Thanks again for your time and help 
It works !

**Comment by cedlemo** [comment]
> Thanks again for your time and help

It is the least I can do. Don't hesistate to create issue when you need help or if something bother you.
