### ISSUE TITLE
I'm getting a launch failure

### ISSUE THREAD

**Issue by SolarAquarion** [cedlemo/topinambour#4]
/usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:20:in `alias_method': undefined method `parse' for class `#<Class:Gdk::Color>' (NameError)
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:20:in `singleton class'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:19:in `<class:Color>'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:18:in `<module:Gdk>'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/loader.rb:125:in `require_post_libraries'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/loader.rb:61:in `post_load'
	from /usr/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.6/lib/gobject-introspection/loader.rb:45:in `load'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/loader.rb:20:in `load'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3.rb:57:in `init'
	from /usr/lib/ruby/gems/2.4.0/gems/gtk3-3.1.6/lib/gtk3.rb:64:in `init'
	from /usr/lib/ruby/gems/2.4.0/gems/vte3-3.1.6/lib/vte3.rb:36:in `<module:Vte>'
	from /usr/lib/ruby/gems/2.4.0/gems/vte3-3.1.6/lib/vte3.rb:29:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/topinambour-1.0.14/bin/topinambour:23:in `<top (required)>'
	from /usr/bin/topinambour:22:in `load'
	from /usr/bin/topinambour:22:in `<main>'

**Comment by cedlemo** [comment]
Hi @SolarAquarion ,

I think that it is related to the Gtk3 gems, there is a similar issue here : 

https://github.com/ruby-gnome2/ruby-gnome2/issues/1037

Could you provide more informations ?:

* What system, distro do you use ? 
* How did you install the gems ?
* What are the versions of Gtk+ ?
* Do you use a Gnome testing version ?

**Comment by SolarAquarion** [comment]
ArchLinux
From the quarry repo
3.22.15
No

**Comment by SolarAquarion** [comment]
The problem is that I had GTk4 installed

**Comment by SolarAquarion** [comment]
How do i change fonts?

**Comment by SolarAquarion** [comment]
So Ruby gtk3 will fail if GTk4 is installed

**Comment by cedlemo** [comment]
> So Ruby gtk3 will fail if GTk4 is installed

For now but I am sure that this issue will be fixed soon.
